import { generateMappings } from "../generalMappings";

export const levelSelectionStage1Mappings = generateMappings("level-selection-stage-1-tileset");

export const levelSelectionLayout = [
  [
    "                                          ",
    "                                          ",
    "                                          ",
    "                                          ",
    "                                          ",
    "                                          ",
    "                                          ",
    "                                          ",
    "                                          ",
    "                                          ",
    "                                          ",
    "                                          ",
    "                                          ",
    "                                          ",
    "                                          ",
    "                           *              ",
    "                           *              ",
    "                           *              ",
    "                   *       *              ",
    "                           *              ",
    "                       *   *              ",
    "                       *   *              ",
    "                       *   *              ",
    "                       *   *              ",
    "                                          ",
  ],
  [
    "******************************************",
    "*                                        *",
    "*                                        *",
    "*                                        *",
    "*                                        *",
    "*           01112                        *",
    "*           34445              hddde     *",
    "*           6777i              g8889     *",
    "*                              g8889     *",
    "*                              g8889     *",
    "*                              g8889 hddd*",
    "*111112                        g8889 g888*",
    "*aaaab5                        g8889 g888*",
    "*abbb4i                        g8hdddddde*",
    "*a4445                     0111111g888889*",
    "*a4cc5                     aaaaaaaaaaaaaa*",
    "*accc5                     aaaaaaaaaaaaaa*",
    "*accc5     011111112       aaaaaaaaaaaaaa*",
    "*accf1111111jaaaaaa5       aabbbbbaaaaaaa*",
    "*1111jaaaaaaaaaaaaaf1112   aacccccbbbbbbb*",
    "*aaaaaabbbbbbbbbbbbbbbb5   aacccccccccccc*",
    "*aaabbbcc4cccccccc4cc4c5   aac44cc4ccc4cc*",
    "*aaac4ccccc4cc4ccc4cccc5   aaccccc4c4cc4c*",
    "*aaac4cc4ccc4cc4ccc4c4c5   aac4cc4cc4cc4c*",
  ],
];
