import { generateMappingsLevelSelection } from "./generateMapping";

export const levelSelectionStage1Mappings = generateMappingsLevelSelection("level-selection-stage-1-tileset");

export const levelSelectionLayout = [
  [
    "                                          ",
    "*                                        *",
    "*                                        *",
    "*             ()                         *",
    "*                                        *",
    "*                                        *",
    "*                                        *",
    "*                                        *",
    "*                                     () *",
    "*  ()                                     ",
    "*                                        *",
    "*                                        *",
    "*                                        *",
    "*                                8       *",
    "*                                 8      *",
    "*              ()          *             *",
    "*                          *             *",
    "*                          *             *",
    "*                  *       *             *",
    "*                          *             *",
    "*                      *   *             *",
    "*                      *   *             *",
    "*                      *   *             *",
    "*                      *   *             *",
    "*                                        *",
  ],
  [
    "******************************************",
    "                                          ",
    "                                          ",
    "              =?                          ",
    "              []                          ",
    "            011112                        ",
    "            344445             hddde      ",
    "            67777i             g8889      ",
    "                               g8889  &/  ",
    "   !#                          g8889  []  ",
    "   []                          g8889 hdddd",
    "1111112                        g8889 g8888",
    "aaaaab5                        g8889 g8888",
    "aabbb4i                        g8hddddddde",
    "aa4445                     0111111g8888889",
    "aa4cc5         $%          aaaaaaaaaaaaaaa",
    "aaccc5         []          aaaaaaaaaaaaaaa",
    "aaccc5     011111112       aaaaaaaaaaaaaaa",
    "aaccf1111111jaaaaaa5       aabbbbbaaaaaaaa",
    "11111jaaaaaaaaaaaaaf1112   aacccccbbbbbbbb",
    "aaaaaaabbbbbbbbbbbbbbbb5   aaccccccccccccc",
    "aaaabbbcc4cccccccc4cc4c5   aac44cc4ccc4ccc",
    "aaaac4ccccc4cc4ccc4cccc5   aaccccc4c4cc4cc",
    "aaaac4cc4ccc4cc4ccc4c4c5   aac4cc4cc4cc4cc",
  ],
];
