import { generateLevelMapping } from "../generateLevelMapping";

export const level4Mappings = generateLevelMapping("level-4-tileset");

export const level4Layout = [
  [
    "******************************",
    "*                            *",
    "*                            *",
    "*                            *",
    "*                            *",
    "*                            *",
    "*                            *",
    "*                            *",
    "*                            *",
    "*                            *",
    "*                            *",
    "*                            *",
    "*                            *",
    "*                            *",
    "*                            *",
    "*                            *",
    "*                            *",
    "*                            *",
    "*                            *",
    "*                            *",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
  ],
  [
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                          (   ",
    "                          )   ",
    "011111111111111111111111111112",
    "3                            5",
    "3                            5",
    "3                            5",
  ],
];
