import { generateLevelMapping } from "../generateLevelMapping";

export const level3Mappings = generateLevelMapping("level-3-tileset");

export const level3Layout = [
  [
    "                                                                                                                                                       ",
    "                                                                                                                                                       ",
    "                                                                                                                                                       ",
    "                                                                                                                                                       ",
    "                                                                                                                                                       ",
    "                                                                                                                                                       ",
    "                                                                                                                                                       ",
    "                                                                                                                                                       ",
    "                                                                                                                                                       ",
    "                                                                                                                                                       ",
    "                                                                                                                                                       ",
    "                                                                                           *     *                                                     ",
    "                                                                                                 *                                                     ",
    "                                        *                                                        *                                                     ",
    "                                                                                                 *                                                     ",
    "                                   *                                                             *                                                     ",
    "                                                                                                 *                                                     ",
    "                    *                                                                            *                                                     ",
    "                    *                                                                            *                                                     ",
    "                                                                                                 *                                                     ",
    "                                                                                                 5                                                    *",
    "*                                                                                                5                                                    *",
    "*                                                                                                5                                                    *",
    "*                                                                                                5                                                    *",
  ],
  [
    "                                                                                                                                                       ",
    "                                                                                                                                                       ",
    "                                                                                                                                                       ",
    "                                                                                                                                                       ",
    "                                                                                                            012012012012012012012                      ",
    "             e   e     ed                                                                                                                          (   ",
    "           01111111111112                                                                               012                                 ee     )  e",
    "         ab3            59                                                                                                                0111111111112",
    "           3            5                                                                           012                                   3           5",
    "c  c     ab3            59aa                                                                 c  cd                                       b3           5",
    "1112       3            5                                                                  0111112                                        3           5",
    "   5    aab3            59aaaa           c e                                               3     5                                      ab3           5",
    "   59a     3            5               01129aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab3     59                                    d d3           5",
    "   5       3            5           c c 3  5                                               3     5 a                                0111113           5",
    "   59a     3            5          011112  5                                               3     5  a                              c3     3           5",
    "   5       3         c  5 d        3    5  5                                               3     5   a     c      e              011112   3           5",
    "   59a     3        01111129aaaaaab3    5  5                                               3     5    a   0111111111112        ab3    5   3           5",
    "   5       3      ab3     5        3    5  5                                               3     5     a  3           5          3    5   3           5",
    "   59a   e 3 d      3     5        3    5  5                                               3     5      ab3           59     aaab3    5   3           5",
    " e 5    0111129aaaab3     5        3    5  5                                               3     5e e     3   e      c5   d d  d 3  c 5   3 d  d    dc5",
    "1111111112   5      3     5        3    5  5                                               3     501111111111111111111111111111111111111111111111111112",
    "         5   5      3     5        3    5  5                                               3     53                                                   5",
    "         5   5      3     5        3    5  5                                               3     53                                                   5",
    "         5   5      3     5        3    5  5                                               3     53                                                   5",
  ],
];
